### ISSUE TITLE
map zoomed to 0

### ISSUE THREAD

**Issue by kylewetherald** [ParkWhiz/jquery-parking-map#25]
when there are less than 3 markers, `_setMapToShowMarkers` zooms the map out all the way to 0 to try to fit 3 markers.

**Comment by bluetidepro** [comment]
@kylewetherald I don't think this project hasn't been updated in some time, and I actually don't even work at ParkWhiz anymore (this was a project I had been doing while I was there). I would try to contact @mstratman (email: `mark (at) parkwhiz (dot) com`) and see if there is a newer version of this or something similar! :smile:

**Comment by mstratman** [comment]
Thanks @kylewetherald and @jarretth 
Sorry for the long delay.
